//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitness.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******************************.
        /// </summary>
        internal static string Fitness_Initialize {
            get {
                return ResourceManager.GetString("Fitness_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation number .
        /// </summary>
        internal static string Fitness_Initialize_Generation_number_ {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Generation_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading NFL data ....
        /// </summary>
        internal static string Fitness_Initialize_Reading_NFL_data____ {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Reading_NFL_data____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading NFL data finished!.
        /// </summary>
        internal static string Fitness_Initialize_Reading_NFL_data_finished_ {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Reading_NFL_data_finished_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading signals ....
        /// </summary>
        internal static string Fitness_Initialize_Reading_signals {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Reading_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading signals finished!.
        /// </summary>
        internal static string Fitness_Initialize_Reading_signals_finished_ {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Reading_signals_finished_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading signals names ....
        /// </summary>
        internal static string Fitness_Initialize_Reading_signals_names____ {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Reading_signals_names____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading signals names finished!.
        /// </summary>
        internal static string Fitness_Initialize_Reading_signals_names_finished_ {
            get {
                return ResourceManager.GetString("Fitness_Initialize_Reading_signals_names_finished_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20060907,TH,1,MIA,AFCEast,PITT,AFCNorth,1,0,0,0,1.5,34.5,105,17,28,15,20,18,38,38,143,37,25,18,15,240,196,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///20060907,TH,1,PITT,AFCNorth,MIA,AFCEast,1,1,0,1,-1.5,34.5,-125,28,17,20,15,38,18,143,38,25,37,15,18,196,240,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///20060910,SU,1,DENV,AFCWest,STL,NFCWest,1,0,1,1,-3.5,45.5,-200,10,18,17,16,25,28,161,125,26,34,13,18,98,195,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NFLOutput {
            get {
                return ResourceManager.GetString("NFLOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE,DAY,TEAM,DIV,OTEAM,ODIV,SPREAD,OU,ML,PT,PTA,Favorite,Underdog,Home,Away,Winning Record,Losing Record,Spread -3 or More,Spread -5 or More,Spread -7 or More,Spread -8 or More,Spread -10 or More,Spread -12 or More,Spread -15 or More,Spread -20 or More,Spread -3 or Less,Spread -5 or Less,Spread -7 or Less,Spread -8 or Less,Spread -10 or Less,Spread -12 or Less,Spread -15 or Less,Spread -20 or Less,Spread +3 or Less,Spread +5 or Less,Spread +7 or Less,Spread +8 or Less,Spread +10 or Less,Spread +12 or Less, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Signals {
            get {
                return ResourceManager.GetString("Signals", resourceCulture);
            }
        }
    }
}
